/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary": "#d0cecd",
        "on-tertiary": "#313030",
        "error-container": "#93000a",
        "on-surface-variant": "#d0c5af",
        "tertiary-fixed": "#e5e2e1",
        "secondary": "#ecffe3",
        "surface-container-high": "#282a2b",
        "tertiary-container": "#b5b2b2",
        "surface-container-highest": "#333535",
        "on-background": "#e2e2e2",
        "inverse-surface": "#e2e2e2",
        "on-tertiary-fixed": "#1c1b1b",
        "on-surface": "#e2e2e2",
        "secondary-fixed-dim": "#00e639",
        "primary-fixed-dim": "#e9c349",
        "error": "#ffb4ab",
        "surface-bright": "#38393a",
        "outline": "#99907c",
        "secondary-container": "#13ff43",
        "surface-container": "#1e2020",
        "on-tertiary-fixed-variant": "#474646",
        "secondary-fixed": "#72ff70",
        "surface": "#121414",
        "on-primary-fixed-variant": "#574500",
        "surface-variant": "#333535",
        "surface-dim": "#121414",
        "on-secondary": "#003907",
        "inverse-primary": "#735c00",
        "on-primary": "#3c2f00",
        "primary-container": "#d4af37",
        "on-tertiary-container": "#464545",
        "surface-container-low": "#1a1c1c",
        "outline-variant": "#4d4635",
        "on-secondary-fixed-variant": "#00530e",
        "surface-tint": "#e9c349",
        "on-primary-container": "#554300",
        "primary": "#f2ca50",
        "inverse-on-surface": "#2f3131",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#0d0e0f",
        "on-secondary-container": "#007117",
        "background": "#121414",
        "tertiary-fixed-dim": "#c9c6c5",
        "on-error": "#690005",
        "on-primary-fixed": "#241a00",
        "on-secondary-fixed": "#002203",
        "primary-fixed": "#ffe088"
      },
      fontFamily: {
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "terminal-sm": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
};
